// Code generated by entc, DO NOT EDIT.

package place

const (
	// Label holds the string label denoting the place type in the database.
	Label = "place"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPLACE holds the string denoting the place field in the database.
	FieldPLACE = "place"

	// EdgePlaceActi holds the string denoting the place_acti edge name in mutations.
	EdgePlaceActi = "place_acti"

	// Table holds the table name of the place in the database.
	Table = "places"
	// PlaceActiTable is the table the holds the place_acti relation/edge.
	PlaceActiTable = "activities"
	// PlaceActiInverseTable is the table name for the Activity entity.
	// It exists in this package in order to avoid circular dependency with the "activity" package.
	PlaceActiInverseTable = "activities"
	// PlaceActiColumn is the table column denoting the place_acti relation/edge.
	PlaceActiColumn = "place_place_acti"
)

// Columns holds all SQL columns for place fields.
var Columns = []string{
	FieldID,
	FieldPLACE,
}

var (
	// PLACEValidator is a validator for the "PLACE" field. It is called by the builders before save.
	PLACEValidator func(string) error
)
