// Code generated by entc, DO NOT EDIT.

package district

const (
	// Label holds the string label denoting the district type in the database.
	Label = "district"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDistrict holds the string denoting the district field in the database.
	FieldDistrict = "district"

	// EdgeDistSubd holds the string denoting the dist_subd edge name in mutations.
	EdgeDistSubd = "dist_subd"
	// EdgeDistPost holds the string denoting the dist_post edge name in mutations.
	EdgeDistPost = "dist_post"
	// EdgeDistProv holds the string denoting the dist_prov edge name in mutations.
	EdgeDistProv = "dist_prov"

	// Table holds the table name of the district in the database.
	Table = "districts"
	// DistSubdTable is the table the holds the dist_subd relation/edge.
	DistSubdTable = "districts"
	// DistSubdInverseTable is the table name for the Subdistrict entity.
	// It exists in this package in order to avoid circular dependency with the "subdistrict" package.
	DistSubdInverseTable = "subdistricts"
	// DistSubdColumn is the table column denoting the dist_subd relation/edge.
	DistSubdColumn = "subdistrict_subd_dist"
	// DistPostTable is the table the holds the dist_post relation/edge.
	DistPostTable = "districts"
	// DistPostInverseTable is the table name for the Postal entity.
	// It exists in this package in order to avoid circular dependency with the "postal" package.
	DistPostInverseTable = "postals"
	// DistPostColumn is the table column denoting the dist_post relation/edge.
	DistPostColumn = "postal_post_dist"
	// DistProvTable is the table the holds the dist_prov relation/edge.
	DistProvTable = "provinces"
	// DistProvInverseTable is the table name for the Province entity.
	// It exists in this package in order to avoid circular dependency with the "province" package.
	DistProvInverseTable = "provinces"
	// DistProvColumn is the table column denoting the dist_prov relation/edge.
	DistProvColumn = "district_dist_prov"
)

// Columns holds all SQL columns for district fields.
var Columns = []string{
	FieldID,
	FieldDistrict,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the District type.
var ForeignKeys = []string{
	"postal_post_dist",
	"subdistrict_subd_dist",
}

var (
	// DistrictValidator is a validator for the "district" field. It is called by the builders before save.
	DistrictValidator func(string) error
)
