// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Activity is the predicate function for activity builders.
type Activity func(*sql.Selector)

// Agency is the predicate function for agency builders.
type Agency func(*sql.Selector)

// Continent is the predicate function for continent builders.
type Continent func(*sql.Selector)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Degree is the predicate function for degree builders.
type Degree func(*sql.Selector)

// Emp is the predicate function for emp builders.
type Emp func(*sql.Selector)

// Faculty is the predicate function for faculty builders.
type Faculty func(*sql.Selector)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// Institution is the predicate function for institution builders.
type Institution func(*sql.Selector)

// Place is the predicate function for place builders.
type Place func(*sql.Selector)

// Prefix is the predicate function for prefix builders.
type Prefix func(*sql.Selector)

// Professor is the predicate function for professor builders.
type Professor func(*sql.Selector)

// Professorship is the predicate function for professorship builders.
type Professorship func(*sql.Selector)

// Province is the predicate function for province builders.
type Province func(*sql.Selector)

// Region is the predicate function for region builders.
type Region func(*sql.Selector)

// Results is the predicate function for results builders.
type Results func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)

// Term is the predicate function for term builders.
type Term func(*sql.Selector)

// Year is the predicate function for year builders.
type Year func(*sql.Selector)
