// Code generated by entc, DO NOT EDIT.

package year

const (
	// Label holds the string label denoting the year type in the database.
	Label = "year"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldYears holds the string denoting the years field in the database.
	FieldYears = "years"

	// EdgeYearTerm holds the string denoting the year_term edge name in mutations.
	EdgeYearTerm = "year_term"
	// EdgeYearResu holds the string denoting the year_resu edge name in mutations.
	EdgeYearResu = "year_resu"
	// EdgeYearActi holds the string denoting the year_acti edge name in mutations.
	EdgeYearActi = "year_acti"

	// Table holds the table name of the year in the database.
	Table = "years"
	// YearTermTable is the table the holds the year_term relation/edge.
	YearTermTable = "terms"
	// YearTermInverseTable is the table name for the Term entity.
	// It exists in this package in order to avoid circular dependency with the "term" package.
	YearTermInverseTable = "terms"
	// YearTermColumn is the table column denoting the year_term relation/edge.
	YearTermColumn = "year_year_term"
	// YearResuTable is the table the holds the year_resu relation/edge.
	YearResuTable = "results"
	// YearResuInverseTable is the table name for the Results entity.
	// It exists in this package in order to avoid circular dependency with the "results" package.
	YearResuInverseTable = "results"
	// YearResuColumn is the table column denoting the year_resu relation/edge.
	YearResuColumn = "year_year_resu"
	// YearActiTable is the table the holds the year_acti relation/edge.
	YearActiTable = "activities"
	// YearActiInverseTable is the table name for the Activity entity.
	// It exists in this package in order to avoid circular dependency with the "activity" package.
	YearActiInverseTable = "activities"
	// YearActiColumn is the table column denoting the year_acti relation/edge.
	YearActiColumn = "year_year_acti"
)

// Columns holds all SQL columns for year fields.
var Columns = []string{
	FieldID,
	FieldYears,
}

var (
	// YearsValidator is a validator for the "years" field. It is called by the builders before save.
	YearsValidator func(int) error
)
