// Code generated by entc, DO NOT EDIT.

package agency

const (
	// Label holds the string label denoting the agency type in the database.
	Label = "agency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAGENCY holds the string denoting the agency field in the database.
	FieldAGENCY = "agency"

	// EdgeAgenActi holds the string denoting the agen_acti edge name in mutations.
	EdgeAgenActi = "agen_acti"

	// Table holds the table name of the agency in the database.
	Table = "agencies"
	// AgenActiTable is the table the holds the agen_acti relation/edge.
	AgenActiTable = "activities"
	// AgenActiInverseTable is the table name for the Activity entity.
	// It exists in this package in order to avoid circular dependency with the "activity" package.
	AgenActiInverseTable = "activities"
	// AgenActiColumn is the table column denoting the agen_acti relation/edge.
	AgenActiColumn = "agency_agen_acti"
)

// Columns holds all SQL columns for agency fields.
var Columns = []string{
	FieldID,
	FieldAGENCY,
}

var (
	// AGENCYValidator is a validator for the "AGENCY" field. It is called by the builders before save.
	AGENCYValidator func(string) error
)
