// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team17/app/ent/activity"
	"github.com/sut63/team17/app/ent/agency"
)

// AgencyCreate is the builder for creating a Agency entity.
type AgencyCreate struct {
	config
	mutation *AgencyMutation
	hooks    []Hook
}

// SetAGENCY sets the AGENCY field.
func (ac *AgencyCreate) SetAGENCY(s string) *AgencyCreate {
	ac.mutation.SetAGENCY(s)
	return ac
}

// AddAgenActiIDs adds the agen_acti edge to Activity by ids.
func (ac *AgencyCreate) AddAgenActiIDs(ids ...int) *AgencyCreate {
	ac.mutation.AddAgenActiIDs(ids...)
	return ac
}

// AddAgenActi adds the agen_acti edges to Activity.
func (ac *AgencyCreate) AddAgenActi(a ...*Activity) *AgencyCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ac.AddAgenActiIDs(ids...)
}

// Mutation returns the AgencyMutation object of the builder.
func (ac *AgencyCreate) Mutation() *AgencyMutation {
	return ac.mutation
}

// Save creates the Agency in the database.
func (ac *AgencyCreate) Save(ctx context.Context) (*Agency, error) {
	if _, ok := ac.mutation.AGENCY(); !ok {
		return nil, &ValidationError{Name: "AGENCY", err: errors.New("ent: missing required field \"AGENCY\"")}
	}
	if v, ok := ac.mutation.AGENCY(); ok {
		if err := agency.AGENCYValidator(v); err != nil {
			return nil, &ValidationError{Name: "AGENCY", err: fmt.Errorf("ent: validator failed for field \"AGENCY\": %w", err)}
		}
	}
	var (
		err  error
		node *Agency
	)
	if len(ac.hooks) == 0 {
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AgencyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AgencyCreate) SaveX(ctx context.Context) *Agency {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ac *AgencyCreate) sqlSave(ctx context.Context) (*Agency, error) {
	a, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	a.ID = int(id)
	return a, nil
}

func (ac *AgencyCreate) createSpec() (*Agency, *sqlgraph.CreateSpec) {
	var (
		a     = &Agency{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: agency.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: agency.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.AGENCY(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: agency.FieldAGENCY,
		})
		a.AGENCY = value
	}
	if nodes := ac.mutation.AgenActiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agency.AgenActiTable,
			Columns: []string{agency.AgenActiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: activity.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return a, _spec
}
