// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team17/app/ent/district"
	"github.com/sut63/team17/app/ent/postal"
	"github.com/sut63/team17/app/ent/predicate"
)

// PostalUpdate is the builder for updating Postal entities.
type PostalUpdate struct {
	config
	hooks      []Hook
	mutation   *PostalMutation
	predicates []predicate.Postal
}

// Where adds a new predicate for the builder.
func (pu *PostalUpdate) Where(ps ...predicate.Postal) *PostalUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetPostal sets the postal field.
func (pu *PostalUpdate) SetPostal(s string) *PostalUpdate {
	pu.mutation.SetPostal(s)
	return pu
}

// AddPostDistIDs adds the post_dist edge to District by ids.
func (pu *PostalUpdate) AddPostDistIDs(ids ...int) *PostalUpdate {
	pu.mutation.AddPostDistIDs(ids...)
	return pu
}

// AddPostDist adds the post_dist edges to District.
func (pu *PostalUpdate) AddPostDist(d ...*District) *PostalUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pu.AddPostDistIDs(ids...)
}

// Mutation returns the PostalMutation object of the builder.
func (pu *PostalUpdate) Mutation() *PostalMutation {
	return pu.mutation
}

// RemovePostDistIDs removes the post_dist edge to District by ids.
func (pu *PostalUpdate) RemovePostDistIDs(ids ...int) *PostalUpdate {
	pu.mutation.RemovePostDistIDs(ids...)
	return pu
}

// RemovePostDist removes post_dist edges to District.
func (pu *PostalUpdate) RemovePostDist(d ...*District) *PostalUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pu.RemovePostDistIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PostalUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := pu.mutation.Postal(); ok {
		if err := postal.PostalValidator(v); err != nil {
			return 0, &ValidationError{Name: "postal", err: fmt.Errorf("ent: validator failed for field \"postal\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostalMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PostalUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PostalUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PostalUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PostalUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   postal.Table,
			Columns: postal.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postal.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Postal(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: postal.FieldPostal,
		})
	}
	if nodes := pu.mutation.RemovedPostDistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postal.PostDistTable,
			Columns: []string{postal.PostDistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.PostDistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postal.PostDistTable,
			Columns: []string{postal.PostDistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postal.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PostalUpdateOne is the builder for updating a single Postal entity.
type PostalUpdateOne struct {
	config
	hooks    []Hook
	mutation *PostalMutation
}

// SetPostal sets the postal field.
func (puo *PostalUpdateOne) SetPostal(s string) *PostalUpdateOne {
	puo.mutation.SetPostal(s)
	return puo
}

// AddPostDistIDs adds the post_dist edge to District by ids.
func (puo *PostalUpdateOne) AddPostDistIDs(ids ...int) *PostalUpdateOne {
	puo.mutation.AddPostDistIDs(ids...)
	return puo
}

// AddPostDist adds the post_dist edges to District.
func (puo *PostalUpdateOne) AddPostDist(d ...*District) *PostalUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return puo.AddPostDistIDs(ids...)
}

// Mutation returns the PostalMutation object of the builder.
func (puo *PostalUpdateOne) Mutation() *PostalMutation {
	return puo.mutation
}

// RemovePostDistIDs removes the post_dist edge to District by ids.
func (puo *PostalUpdateOne) RemovePostDistIDs(ids ...int) *PostalUpdateOne {
	puo.mutation.RemovePostDistIDs(ids...)
	return puo
}

// RemovePostDist removes post_dist edges to District.
func (puo *PostalUpdateOne) RemovePostDist(d ...*District) *PostalUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return puo.RemovePostDistIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (puo *PostalUpdateOne) Save(ctx context.Context) (*Postal, error) {
	if v, ok := puo.mutation.Postal(); ok {
		if err := postal.PostalValidator(v); err != nil {
			return nil, &ValidationError{Name: "postal", err: fmt.Errorf("ent: validator failed for field \"postal\": %w", err)}
		}
	}

	var (
		err  error
		node *Postal
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostalMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PostalUpdateOne) SaveX(ctx context.Context) *Postal {
	po, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return po
}

// Exec executes the query on the entity.
func (puo *PostalUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PostalUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PostalUpdateOne) sqlSave(ctx context.Context) (po *Postal, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   postal.Table,
			Columns: postal.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postal.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Postal.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.Postal(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: postal.FieldPostal,
		})
	}
	if nodes := puo.mutation.RemovedPostDistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postal.PostDistTable,
			Columns: []string{postal.PostDistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.PostDistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postal.PostDistTable,
			Columns: []string{postal.PostDistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	po = &Postal{config: puo.config}
	_spec.Assign = po.assignValues
	_spec.ScanValues = po.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postal.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return po, nil
}
