// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/sut63/team17/app/ent/prefix"
)

// Prefix is the model entity for the Prefix schema.
type Prefix struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Prefix holds the value of the "prefix" field.
	Prefix string `json:"prefix,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PrefixQuery when eager-loading is set.
	Edges PrefixEdges `json:"edges"`
}

// PrefixEdges holds the relations/edges for other nodes in the graph.
type PrefixEdges struct {
	// PreProf holds the value of the pre_prof edge.
	PreProf []*Professor
	// PrefStud holds the value of the pref_stud edge.
	PrefStud []*Student
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PreProfOrErr returns the PreProf value or an error if the edge
// was not loaded in eager-loading.
func (e PrefixEdges) PreProfOrErr() ([]*Professor, error) {
	if e.loadedTypes[0] {
		return e.PreProf, nil
	}
	return nil, &NotLoadedError{edge: "pre_prof"}
}

// PrefStudOrErr returns the PrefStud value or an error if the edge
// was not loaded in eager-loading.
func (e PrefixEdges) PrefStudOrErr() ([]*Student, error) {
	if e.loadedTypes[1] {
		return e.PrefStud, nil
	}
	return nil, &NotLoadedError{edge: "pref_stud"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Prefix) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // prefix
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Prefix fields.
func (pr *Prefix) assignValues(values ...interface{}) error {
	if m, n := len(values), len(prefix.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pr.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field prefix", values[0])
	} else if value.Valid {
		pr.Prefix = value.String
	}
	return nil
}

// QueryPreProf queries the pre_prof edge of the Prefix.
func (pr *Prefix) QueryPreProf() *ProfessorQuery {
	return (&PrefixClient{config: pr.config}).QueryPreProf(pr)
}

// QueryPrefStud queries the pref_stud edge of the Prefix.
func (pr *Prefix) QueryPrefStud() *StudentQuery {
	return (&PrefixClient{config: pr.config}).QueryPrefStud(pr)
}

// Update returns a builder for updating this Prefix.
// Note that, you need to call Prefix.Unwrap() before calling this method, if this Prefix
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Prefix) Update() *PrefixUpdateOne {
	return (&PrefixClient{config: pr.config}).UpdateOne(pr)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pr *Prefix) Unwrap() *Prefix {
	tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Prefix is not a transactional entity")
	}
	pr.config.driver = tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Prefix) String() string {
	var builder strings.Builder
	builder.WriteString("Prefix(")
	builder.WriteString(fmt.Sprintf("id=%v", pr.ID))
	builder.WriteString(", prefix=")
	builder.WriteString(pr.Prefix)
	builder.WriteByte(')')
	return builder.String()
}

// Prefixes is a parsable slice of Prefix.
type Prefixes []*Prefix

func (pr Prefixes) config(cfg config) {
	for _i := range pr {
		pr[_i].config = cfg
	}
}
