// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/sut63/team17/app/ent/district"
	"github.com/sut63/team17/app/ent/province"
	"github.com/sut63/team17/app/ent/region"
)

// Province is the model entity for the Province schema.
type Province struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProvinceQuery when eager-loading is set.
	Edges              ProvinceEdges `json:"edges"`
	district_dist_prov *int
	region_regi_prov   *int
}

// ProvinceEdges holds the relations/edges for other nodes in the graph.
type ProvinceEdges struct {
	// ProvRegi holds the value of the prov_regi edge.
	ProvRegi *Region
	// ProvDist holds the value of the prov_dist edge.
	ProvDist *District
	// ProvStud holds the value of the prov_stud edge.
	ProvStud []*Student
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProvRegiOrErr returns the ProvRegi value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProvinceEdges) ProvRegiOrErr() (*Region, error) {
	if e.loadedTypes[0] {
		if e.ProvRegi == nil {
			// The edge prov_regi was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: region.Label}
		}
		return e.ProvRegi, nil
	}
	return nil, &NotLoadedError{edge: "prov_regi"}
}

// ProvDistOrErr returns the ProvDist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProvinceEdges) ProvDistOrErr() (*District, error) {
	if e.loadedTypes[1] {
		if e.ProvDist == nil {
			// The edge prov_dist was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: district.Label}
		}
		return e.ProvDist, nil
	}
	return nil, &NotLoadedError{edge: "prov_dist"}
}

// ProvStudOrErr returns the ProvStud value or an error if the edge
// was not loaded in eager-loading.
func (e ProvinceEdges) ProvStudOrErr() ([]*Student, error) {
	if e.loadedTypes[2] {
		return e.ProvStud, nil
	}
	return nil, &NotLoadedError{edge: "prov_stud"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Province) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Province) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // district_dist_prov
		&sql.NullInt64{}, // region_regi_prov
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Province fields.
func (pr *Province) assignValues(values ...interface{}) error {
	if m, n := len(values), len(province.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pr.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		pr.Name = value.String
	}
	values = values[1:]
	if len(values) == len(province.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field district_dist_prov", value)
		} else if value.Valid {
			pr.district_dist_prov = new(int)
			*pr.district_dist_prov = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field region_regi_prov", value)
		} else if value.Valid {
			pr.region_regi_prov = new(int)
			*pr.region_regi_prov = int(value.Int64)
		}
	}
	return nil
}

// QueryProvRegi queries the prov_regi edge of the Province.
func (pr *Province) QueryProvRegi() *RegionQuery {
	return (&ProvinceClient{config: pr.config}).QueryProvRegi(pr)
}

// QueryProvDist queries the prov_dist edge of the Province.
func (pr *Province) QueryProvDist() *DistrictQuery {
	return (&ProvinceClient{config: pr.config}).QueryProvDist(pr)
}

// QueryProvStud queries the prov_stud edge of the Province.
func (pr *Province) QueryProvStud() *StudentQuery {
	return (&ProvinceClient{config: pr.config}).QueryProvStud(pr)
}

// Update returns a builder for updating this Province.
// Note that, you need to call Province.Unwrap() before calling this method, if this Province
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Province) Update() *ProvinceUpdateOne {
	return (&ProvinceClient{config: pr.config}).UpdateOne(pr)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pr *Province) Unwrap() *Province {
	tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Province is not a transactional entity")
	}
	pr.config.driver = tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Province) String() string {
	var builder strings.Builder
	builder.WriteString("Province(")
	builder.WriteString(fmt.Sprintf("id=%v", pr.ID))
	builder.WriteString(", name=")
	builder.WriteString(pr.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Provinces is a parsable slice of Province.
type Provinces []*Province

func (pr Provinces) config(cfg config) {
	for _i := range pr {
		pr[_i].config = cfg
	}
}
