// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team17/app/ent/predicate"
	"github.com/sut63/team17/app/ent/results"
	"github.com/sut63/team17/app/ent/subject"
)

// SubjectUpdate is the builder for updating Subject entities.
type SubjectUpdate struct {
	config
	hooks      []Hook
	mutation   *SubjectMutation
	predicates []predicate.Subject
}

// Where adds a new predicate for the builder.
func (su *SubjectUpdate) Where(ps ...predicate.Subject) *SubjectUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetCode sets the code field.
func (su *SubjectUpdate) SetCode(i int) *SubjectUpdate {
	su.mutation.ResetCode()
	su.mutation.SetCode(i)
	return su
}

// AddCode adds i to code.
func (su *SubjectUpdate) AddCode(i int) *SubjectUpdate {
	su.mutation.AddCode(i)
	return su
}

// SetSubjects sets the subjects field.
func (su *SubjectUpdate) SetSubjects(s string) *SubjectUpdate {
	su.mutation.SetSubjects(s)
	return su
}

// SetCreditpiont sets the creditpiont field.
func (su *SubjectUpdate) SetCreditpiont(i int) *SubjectUpdate {
	su.mutation.ResetCreditpiont()
	su.mutation.SetCreditpiont(i)
	return su
}

// AddCreditpiont adds i to creditpiont.
func (su *SubjectUpdate) AddCreditpiont(i int) *SubjectUpdate {
	su.mutation.AddCreditpiont(i)
	return su
}

// AddSubjResuIDs adds the subj_resu edge to Results by ids.
func (su *SubjectUpdate) AddSubjResuIDs(ids ...int) *SubjectUpdate {
	su.mutation.AddSubjResuIDs(ids...)
	return su
}

// AddSubjResu adds the subj_resu edges to Results.
func (su *SubjectUpdate) AddSubjResu(r ...*Results) *SubjectUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.AddSubjResuIDs(ids...)
}

// Mutation returns the SubjectMutation object of the builder.
func (su *SubjectUpdate) Mutation() *SubjectMutation {
	return su.mutation
}

// RemoveSubjResuIDs removes the subj_resu edge to Results by ids.
func (su *SubjectUpdate) RemoveSubjResuIDs(ids ...int) *SubjectUpdate {
	su.mutation.RemoveSubjResuIDs(ids...)
	return su
}

// RemoveSubjResu removes subj_resu edges to Results.
func (su *SubjectUpdate) RemoveSubjResu(r ...*Results) *SubjectUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.RemoveSubjResuIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *SubjectUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.Code(); ok {
		if err := subject.CodeValidator(v); err != nil {
			return 0, &ValidationError{Name: "code", err: fmt.Errorf("ent: validator failed for field \"code\": %w", err)}
		}
	}
	if v, ok := su.mutation.Subjects(); ok {
		if err := subject.SubjectsValidator(v); err != nil {
			return 0, &ValidationError{Name: "subjects", err: fmt.Errorf("ent: validator failed for field \"subjects\": %w", err)}
		}
	}
	if v, ok := su.mutation.Creditpiont(); ok {
		if err := subject.CreditpiontValidator(v); err != nil {
			return 0, &ValidationError{Name: "creditpiont", err: fmt.Errorf("ent: validator failed for field \"creditpiont\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SubjectMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SubjectUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SubjectUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SubjectUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SubjectUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   subject.Table,
			Columns: subject.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: subject.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCode,
		})
	}
	if value, ok := su.mutation.AddedCode(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCode,
		})
	}
	if value, ok := su.mutation.Subjects(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subject.FieldSubjects,
		})
	}
	if value, ok := su.mutation.Creditpiont(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCreditpiont,
		})
	}
	if value, ok := su.mutation.AddedCreditpiont(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCreditpiont,
		})
	}
	if nodes := su.mutation.RemovedSubjResuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subject.SubjResuTable,
			Columns: []string{subject.SubjResuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: results.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SubjResuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subject.SubjResuTable,
			Columns: []string{subject.SubjResuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: results.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subject.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// SubjectUpdateOne is the builder for updating a single Subject entity.
type SubjectUpdateOne struct {
	config
	hooks    []Hook
	mutation *SubjectMutation
}

// SetCode sets the code field.
func (suo *SubjectUpdateOne) SetCode(i int) *SubjectUpdateOne {
	suo.mutation.ResetCode()
	suo.mutation.SetCode(i)
	return suo
}

// AddCode adds i to code.
func (suo *SubjectUpdateOne) AddCode(i int) *SubjectUpdateOne {
	suo.mutation.AddCode(i)
	return suo
}

// SetSubjects sets the subjects field.
func (suo *SubjectUpdateOne) SetSubjects(s string) *SubjectUpdateOne {
	suo.mutation.SetSubjects(s)
	return suo
}

// SetCreditpiont sets the creditpiont field.
func (suo *SubjectUpdateOne) SetCreditpiont(i int) *SubjectUpdateOne {
	suo.mutation.ResetCreditpiont()
	suo.mutation.SetCreditpiont(i)
	return suo
}

// AddCreditpiont adds i to creditpiont.
func (suo *SubjectUpdateOne) AddCreditpiont(i int) *SubjectUpdateOne {
	suo.mutation.AddCreditpiont(i)
	return suo
}

// AddSubjResuIDs adds the subj_resu edge to Results by ids.
func (suo *SubjectUpdateOne) AddSubjResuIDs(ids ...int) *SubjectUpdateOne {
	suo.mutation.AddSubjResuIDs(ids...)
	return suo
}

// AddSubjResu adds the subj_resu edges to Results.
func (suo *SubjectUpdateOne) AddSubjResu(r ...*Results) *SubjectUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.AddSubjResuIDs(ids...)
}

// Mutation returns the SubjectMutation object of the builder.
func (suo *SubjectUpdateOne) Mutation() *SubjectMutation {
	return suo.mutation
}

// RemoveSubjResuIDs removes the subj_resu edge to Results by ids.
func (suo *SubjectUpdateOne) RemoveSubjResuIDs(ids ...int) *SubjectUpdateOne {
	suo.mutation.RemoveSubjResuIDs(ids...)
	return suo
}

// RemoveSubjResu removes subj_resu edges to Results.
func (suo *SubjectUpdateOne) RemoveSubjResu(r ...*Results) *SubjectUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.RemoveSubjResuIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *SubjectUpdateOne) Save(ctx context.Context) (*Subject, error) {
	if v, ok := suo.mutation.Code(); ok {
		if err := subject.CodeValidator(v); err != nil {
			return nil, &ValidationError{Name: "code", err: fmt.Errorf("ent: validator failed for field \"code\": %w", err)}
		}
	}
	if v, ok := suo.mutation.Subjects(); ok {
		if err := subject.SubjectsValidator(v); err != nil {
			return nil, &ValidationError{Name: "subjects", err: fmt.Errorf("ent: validator failed for field \"subjects\": %w", err)}
		}
	}
	if v, ok := suo.mutation.Creditpiont(); ok {
		if err := subject.CreditpiontValidator(v); err != nil {
			return nil, &ValidationError{Name: "creditpiont", err: fmt.Errorf("ent: validator failed for field \"creditpiont\": %w", err)}
		}
	}

	var (
		err  error
		node *Subject
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SubjectMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SubjectUpdateOne) SaveX(ctx context.Context) *Subject {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *SubjectUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SubjectUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SubjectUpdateOne) sqlSave(ctx context.Context) (s *Subject, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   subject.Table,
			Columns: subject.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: subject.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Subject.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCode,
		})
	}
	if value, ok := suo.mutation.AddedCode(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCode,
		})
	}
	if value, ok := suo.mutation.Subjects(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subject.FieldSubjects,
		})
	}
	if value, ok := suo.mutation.Creditpiont(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCreditpiont,
		})
	}
	if value, ok := suo.mutation.AddedCreditpiont(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCreditpiont,
		})
	}
	if nodes := suo.mutation.RemovedSubjResuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subject.SubjResuTable,
			Columns: []string{subject.SubjResuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: results.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SubjResuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subject.SubjResuTable,
			Columns: []string{subject.SubjResuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: results.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Subject{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subject.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
