// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team17/app/ent/predicate"
	"github.com/sut63/team17/app/ent/term"
	"github.com/sut63/team17/app/ent/year"
)

// TermUpdate is the builder for updating Term entities.
type TermUpdate struct {
	config
	hooks      []Hook
	mutation   *TermMutation
	predicates []predicate.Term
}

// Where adds a new predicate for the builder.
func (tu *TermUpdate) Where(ps ...predicate.Term) *TermUpdate {
	tu.predicates = append(tu.predicates, ps...)
	return tu
}

// SetSemester sets the semester field.
func (tu *TermUpdate) SetSemester(i int) *TermUpdate {
	tu.mutation.ResetSemester()
	tu.mutation.SetSemester(i)
	return tu
}

// AddSemester adds i to semester.
func (tu *TermUpdate) AddSemester(i int) *TermUpdate {
	tu.mutation.AddSemester(i)
	return tu
}

// SetTermYearID sets the term_year edge to Year by id.
func (tu *TermUpdate) SetTermYearID(id int) *TermUpdate {
	tu.mutation.SetTermYearID(id)
	return tu
}

// SetNillableTermYearID sets the term_year edge to Year by id if the given value is not nil.
func (tu *TermUpdate) SetNillableTermYearID(id *int) *TermUpdate {
	if id != nil {
		tu = tu.SetTermYearID(*id)
	}
	return tu
}

// SetTermYear sets the term_year edge to Year.
func (tu *TermUpdate) SetTermYear(y *Year) *TermUpdate {
	return tu.SetTermYearID(y.ID)
}

// Mutation returns the TermMutation object of the builder.
func (tu *TermUpdate) Mutation() *TermMutation {
	return tu.mutation
}

// ClearTermYear clears the term_year edge to Year.
func (tu *TermUpdate) ClearTermYear() *TermUpdate {
	tu.mutation.ClearTermYear()
	return tu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (tu *TermUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := tu.mutation.Semester(); ok {
		if err := term.SemesterValidator(v); err != nil {
			return 0, &ValidationError{Name: "semester", err: fmt.Errorf("ent: validator failed for field \"semester\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TermMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TermUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TermUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TermUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TermUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   term.Table,
			Columns: term.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: term.FieldID,
			},
		},
	}
	if ps := tu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Semester(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: term.FieldSemester,
		})
	}
	if value, ok := tu.mutation.AddedSemester(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: term.FieldSemester,
		})
	}
	if tu.mutation.TermYearCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   term.TermYearTable,
			Columns: []string{term.TermYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: year.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.TermYearIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   term.TermYearTable,
			Columns: []string{term.TermYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: year.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{term.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// TermUpdateOne is the builder for updating a single Term entity.
type TermUpdateOne struct {
	config
	hooks    []Hook
	mutation *TermMutation
}

// SetSemester sets the semester field.
func (tuo *TermUpdateOne) SetSemester(i int) *TermUpdateOne {
	tuo.mutation.ResetSemester()
	tuo.mutation.SetSemester(i)
	return tuo
}

// AddSemester adds i to semester.
func (tuo *TermUpdateOne) AddSemester(i int) *TermUpdateOne {
	tuo.mutation.AddSemester(i)
	return tuo
}

// SetTermYearID sets the term_year edge to Year by id.
func (tuo *TermUpdateOne) SetTermYearID(id int) *TermUpdateOne {
	tuo.mutation.SetTermYearID(id)
	return tuo
}

// SetNillableTermYearID sets the term_year edge to Year by id if the given value is not nil.
func (tuo *TermUpdateOne) SetNillableTermYearID(id *int) *TermUpdateOne {
	if id != nil {
		tuo = tuo.SetTermYearID(*id)
	}
	return tuo
}

// SetTermYear sets the term_year edge to Year.
func (tuo *TermUpdateOne) SetTermYear(y *Year) *TermUpdateOne {
	return tuo.SetTermYearID(y.ID)
}

// Mutation returns the TermMutation object of the builder.
func (tuo *TermUpdateOne) Mutation() *TermMutation {
	return tuo.mutation
}

// ClearTermYear clears the term_year edge to Year.
func (tuo *TermUpdateOne) ClearTermYear() *TermUpdateOne {
	tuo.mutation.ClearTermYear()
	return tuo
}

// Save executes the query and returns the updated entity.
func (tuo *TermUpdateOne) Save(ctx context.Context) (*Term, error) {
	if v, ok := tuo.mutation.Semester(); ok {
		if err := term.SemesterValidator(v); err != nil {
			return nil, &ValidationError{Name: "semester", err: fmt.Errorf("ent: validator failed for field \"semester\": %w", err)}
		}
	}

	var (
		err  error
		node *Term
	)
	if len(tuo.hooks) == 0 {
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TermMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			mut = tuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TermUpdateOne) SaveX(ctx context.Context) *Term {
	t, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return t
}

// Exec executes the query on the entity.
func (tuo *TermUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TermUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TermUpdateOne) sqlSave(ctx context.Context) (t *Term, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   term.Table,
			Columns: term.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: term.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Term.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := tuo.mutation.Semester(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: term.FieldSemester,
		})
	}
	if value, ok := tuo.mutation.AddedSemester(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: term.FieldSemester,
		})
	}
	if tuo.mutation.TermYearCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   term.TermYearTable,
			Columns: []string{term.TermYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: year.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.TermYearIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   term.TermYearTable,
			Columns: []string{term.TermYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: year.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	t = &Term{config: tuo.config}
	_spec.Assign = t.assignValues
	_spec.ScanValues = t.scanValues()
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{term.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return t, nil
}
