// Code generated by entc, DO NOT EDIT.

package degree

const (
	// Label holds the string label denoting the degree type in the database.
	Label = "degree"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDegree holds the string denoting the degree field in the database.
	FieldDegree = "degree"

	// EdgeDegrStud holds the string denoting the degr_stud edge name in mutations.
	EdgeDegrStud = "degr_stud"
	// EdgeDegrCour holds the string denoting the degr_cour edge name in mutations.
	EdgeDegrCour = "degr_cour"

	// Table holds the table name of the degree in the database.
	Table = "degrees"
	// DegrStudTable is the table the holds the degr_stud relation/edge.
	DegrStudTable = "students"
	// DegrStudInverseTable is the table name for the Student entity.
	// It exists in this package in order to avoid circular dependency with the "student" package.
	DegrStudInverseTable = "students"
	// DegrStudColumn is the table column denoting the degr_stud relation/edge.
	DegrStudColumn = "degree_degr_stud"
	// DegrCourTable is the table the holds the degr_cour relation/edge.
	DegrCourTable = "courses"
	// DegrCourInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	DegrCourInverseTable = "courses"
	// DegrCourColumn is the table column denoting the degr_cour relation/edge.
	DegrCourColumn = "degree_degr_cour"
)

// Columns holds all SQL columns for degree fields.
var Columns = []string{
	FieldID,
	FieldDegree,
}

var (
	// DegreeValidator is a validator for the "degree" field. It is called by the builders before save.
	DegreeValidator func(string) error
)
