// Code generated by entc, DO NOT EDIT.

package professorship

const (
	// Label holds the string label denoting the professorship type in the database.
	Label = "professorship"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProfessorship holds the string denoting the professorship field in the database.
	FieldProfessorship = "professorship"

	// EdgeProsProf holds the string denoting the pros_prof edge name in mutations.
	EdgeProsProf = "pros_prof"

	// Table holds the table name of the professorship in the database.
	Table = "professorships"
	// ProsProfTable is the table the holds the pros_prof relation/edge.
	ProsProfTable = "professors"
	// ProsProfInverseTable is the table name for the Professor entity.
	// It exists in this package in order to avoid circular dependency with the "professor" package.
	ProsProfInverseTable = "professors"
	// ProsProfColumn is the table column denoting the pros_prof relation/edge.
	ProsProfColumn = "professorship_ID"
)

// Columns holds all SQL columns for professorship fields.
var Columns = []string{
	FieldID,
	FieldProfessorship,
}

var (
	// ProfessorshipValidator is a validator for the "professorship" field. It is called by the builders before save.
	ProfessorshipValidator func(string) error
)
