// Code generated by entc, DO NOT EDIT.

package emp

const (
	// Label holds the string label denoting the emp type in the database.
	Label = "emp"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldPass holds the string denoting the pass field in the database.
	FieldPass = "pass"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"

	// Table holds the table name of the emp in the database.
	Table = "emps"
)

// Columns holds all SQL columns for emp fields.
var Columns = []string{
	FieldID,
	FieldUser,
	FieldPass,
	FieldRole,
}

var (
	// UserValidator is a validator for the "user" field. It is called by the builders before save.
	UserValidator func(string) error
	// PassValidator is a validator for the "pass" field. It is called by the builders before save.
	PassValidator func(string) error
)
