// Code generated by entc, DO NOT EDIT.

package institution

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/sut63/team17/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Institution applies equality check predicate on the "institution" field. It's identical to InstitutionEQ.
func Institution(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInstitution), v))
	})
}

// InstitutionEQ applies the EQ predicate on the "institution" field.
func InstitutionEQ(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInstitution), v))
	})
}

// InstitutionNEQ applies the NEQ predicate on the "institution" field.
func InstitutionNEQ(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldInstitution), v))
	})
}

// InstitutionIn applies the In predicate on the "institution" field.
func InstitutionIn(vs ...string) predicate.Institution {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Institution(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldInstitution), v...))
	})
}

// InstitutionNotIn applies the NotIn predicate on the "institution" field.
func InstitutionNotIn(vs ...string) predicate.Institution {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Institution(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldInstitution), v...))
	})
}

// InstitutionGT applies the GT predicate on the "institution" field.
func InstitutionGT(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldInstitution), v))
	})
}

// InstitutionGTE applies the GTE predicate on the "institution" field.
func InstitutionGTE(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldInstitution), v))
	})
}

// InstitutionLT applies the LT predicate on the "institution" field.
func InstitutionLT(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldInstitution), v))
	})
}

// InstitutionLTE applies the LTE predicate on the "institution" field.
func InstitutionLTE(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldInstitution), v))
	})
}

// InstitutionContains applies the Contains predicate on the "institution" field.
func InstitutionContains(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldInstitution), v))
	})
}

// InstitutionHasPrefix applies the HasPrefix predicate on the "institution" field.
func InstitutionHasPrefix(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldInstitution), v))
	})
}

// InstitutionHasSuffix applies the HasSuffix predicate on the "institution" field.
func InstitutionHasSuffix(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldInstitution), v))
	})
}

// InstitutionEqualFold applies the EqualFold predicate on the "institution" field.
func InstitutionEqualFold(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldInstitution), v))
	})
}

// InstitutionContainsFold applies the ContainsFold predicate on the "institution" field.
func InstitutionContainsFold(v string) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldInstitution), v))
	})
}

// HasInstCour applies the HasEdge predicate on the "inst_cour" edge.
func HasInstCour() predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InstCourTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InstCourTable, InstCourColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstCourWith applies the HasEdge predicate on the "inst_cour" edge with a given conditions (other predicates).
func HasInstCourWith(preds ...predicate.Course) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InstCourInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InstCourTable, InstCourColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Institution) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Institution) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Institution) predicate.Institution {
	return predicate.Institution(func(s *sql.Selector) {
		p(s.Not())
	})
}
