// Code generated by entc, DO NOT EDIT.

package postal

const (
	// Label holds the string label denoting the postal type in the database.
	Label = "postal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPostal holds the string denoting the postal field in the database.
	FieldPostal = "postal"

	// EdgePostDist holds the string denoting the post_dist edge name in mutations.
	EdgePostDist = "post_dist"

	// Table holds the table name of the postal in the database.
	Table = "postals"
	// PostDistTable is the table the holds the post_dist relation/edge.
	PostDistTable = "districts"
	// PostDistInverseTable is the table name for the District entity.
	// It exists in this package in order to avoid circular dependency with the "district" package.
	PostDistInverseTable = "districts"
	// PostDistColumn is the table column denoting the post_dist relation/edge.
	PostDistColumn = "postal_post_dist"
)

// Columns holds all SQL columns for postal fields.
var Columns = []string{
	FieldID,
	FieldPostal,
}

var (
	// PostalValidator is a validator for the "postal" field. It is called by the builders before save.
	PostalValidator func(string) error
)
