// Code generated by entc, DO NOT EDIT.

package gender

const (
	// Label holds the string label denoting the gender type in the database.
	Label = "gender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"

	// EdgeGendStud holds the string denoting the gend_stud edge name in mutations.
	EdgeGendStud = "gend_stud"

	// Table holds the table name of the gender in the database.
	Table = "genders"
	// GendStudTable is the table the holds the gend_stud relation/edge.
	GendStudTable = "students"
	// GendStudInverseTable is the table name for the Student entity.
	// It exists in this package in order to avoid circular dependency with the "student" package.
	GendStudInverseTable = "students"
	// GendStudColumn is the table column denoting the gend_stud relation/edge.
	GendStudColumn = "gender_gend_stud"
)

// Columns holds all SQL columns for gender fields.
var Columns = []string{
	FieldID,
	FieldGender,
}
