/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersResults
 */
export interface ControllersResults {
    /**
     * 
     * @type {number}
     * @memberof ControllersResults
     */
    grade?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersResults
     */
    studentID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersResults
     */
    subjectID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersResults
     */
    termID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersResults
     */
    yearID?: number;
}

export function ControllersResultsFromJSON(json: any): ControllersResults {
    return ControllersResultsFromJSONTyped(json, false);
}

export function ControllersResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'grade': !exists(json, 'grade') ? undefined : json['grade'],
        'studentID': !exists(json, 'studentID') ? undefined : json['studentID'],
        'subjectID': !exists(json, 'subjectID') ? undefined : json['subjectID'],
        'termID': !exists(json, 'termID') ? undefined : json['termID'],
        'yearID': !exists(json, 'yearID') ? undefined : json['yearID'],
    };
}

export function ControllersResultsToJSON(value?: ControllersResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'grade': value.grade,
        'studentID': value.studentID,
        'subjectID': value.subjectID,
        'termID': value.termID,
        'yearID': value.yearID,
    };
}


