/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAgencyEdges,
    EntAgencyEdgesFromJSON,
    EntAgencyEdgesFromJSONTyped,
    EntAgencyEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntAgency
 */
export interface EntAgency {
    /**
     * AGENCY holds the value of the "AGENCY" field.
     * @type {string}
     * @memberof EntAgency
     */
    aGENCY?: string;
    /**
     * 
     * @type {EntAgencyEdges}
     * @memberof EntAgency
     */
    edges?: EntAgencyEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntAgency
     */
    id?: number;
}

export function EntAgencyFromJSON(json: any): EntAgency {
    return EntAgencyFromJSONTyped(json, false);
}

export function EntAgencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntAgency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aGENCY': !exists(json, 'AGENCY') ? undefined : json['AGENCY'],
        'edges': !exists(json, 'edges') ? undefined : EntAgencyEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntAgencyToJSON(value?: EntAgency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AGENCY': value.aGENCY,
        'edges': EntAgencyEdgesToJSON(value.edges),
        'id': value.id,
    };
}


