/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCountryEdges,
    EntCountryEdgesFromJSON,
    EntCountryEdgesFromJSONTyped,
    EntCountryEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCountry
 */
export interface EntCountry {
    /**
     * Country holds the value of the "country" field.
     * @type {string}
     * @memberof EntCountry
     */
    country?: string;
    /**
     * 
     * @type {EntCountryEdges}
     * @memberof EntCountry
     */
    edges?: EntCountryEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCountry
     */
    id?: number;
}

export function EntCountryFromJSON(json: any): EntCountry {
    return EntCountryFromJSONTyped(json, false);
}

export function EntCountryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCountry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': !exists(json, 'country') ? undefined : json['country'],
        'edges': !exists(json, 'edges') ? undefined : EntCountryEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntCountryToJSON(value?: EntCountry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'edges': EntCountryEdgesToJSON(value.edges),
        'id': value.id,
    };
}


