/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProvince,
    EntProvinceFromJSON,
    EntProvinceFromJSONTyped,
    EntProvinceToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCountryEdges
 */
export interface EntCountryEdges {
    /**
     * CounProv holds the value of the coun_prov edge.
     * @type {Array<EntProvince>}
     * @memberof EntCountryEdges
     */
    counProv?: Array<EntProvince>;
}

export function EntCountryEdgesFromJSON(json: any): EntCountryEdges {
    return EntCountryEdgesFromJSONTyped(json, false);
}

export function EntCountryEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCountryEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'counProv': !exists(json, 'counProv') ? undefined : ((json['counProv'] as Array<any>).map(EntProvinceFromJSON)),
    };
}

export function EntCountryEdgesToJSON(value?: EntCountryEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'counProv': value.counProv === undefined ? undefined : ((value.counProv as Array<any>).map(EntProvinceToJSON)),
    };
}


