/* tslint:disable */
/* eslint-disable */
/**
 * SUT SE Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDistrictEdges,
    EntDistrictEdgesFromJSON,
    EntDistrictEdgesFromJSONTyped,
    EntDistrictEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDistrict
 */
export interface EntDistrict {
    /**
     * District holds the value of the "district" field.
     * @type {string}
     * @memberof EntDistrict
     */
    district?: string;
    /**
     * 
     * @type {EntDistrictEdges}
     * @memberof EntDistrict
     */
    edges?: EntDistrictEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDistrict
     */
    id?: number;
}

export function EntDistrictFromJSON(json: any): EntDistrict {
    return EntDistrictFromJSONTyped(json, false);
}

export function EntDistrictFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDistrict {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'district': !exists(json, 'district') ? undefined : json['district'],
        'edges': !exists(json, 'edges') ? undefined : EntDistrictEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntDistrictToJSON(value?: EntDistrict | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'district': value.district,
        'edges': EntDistrictEdgesToJSON(value.edges),
        'id': value.id,
    };
}


