/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProfessorshipEdges,
    EntProfessorshipEdgesFromJSON,
    EntProfessorshipEdgesFromJSONTyped,
    EntProfessorshipEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntProfessorship
 */
export interface EntProfessorship {
    /**
     * 
     * @type {EntProfessorshipEdges}
     * @memberof EntProfessorship
     */
    edges?: EntProfessorshipEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntProfessorship
     */
    id?: number;
    /**
     * Professorship holds the value of the "professorship" field.
     * @type {string}
     * @memberof EntProfessorship
     */
    professorship?: string;
}

export function EntProfessorshipFromJSON(json: any): EntProfessorship {
    return EntProfessorshipFromJSONTyped(json, false);
}

export function EntProfessorshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntProfessorship {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntProfessorshipEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'professorship': !exists(json, 'professorship') ? undefined : json['professorship'],
    };
}

export function EntProfessorshipToJSON(value?: EntProfessorship | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntProfessorshipEdgesToJSON(value.edges),
        'id': value.id,
        'professorship': value.professorship,
    };
}


