/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProfessor,
    EntProfessorFromJSON,
    EntProfessorFromJSONTyped,
    EntProfessorToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntProfessorshipEdges
 */
export interface EntProfessorshipEdges {
    /**
     * ProsProf holds the value of the pros_prof edge.
     * @type {Array<EntProfessor>}
     * @memberof EntProfessorshipEdges
     */
    prosProf?: Array<EntProfessor>;
}

export function EntProfessorshipEdgesFromJSON(json: any): EntProfessorshipEdges {
    return EntProfessorshipEdgesFromJSONTyped(json, false);
}

export function EntProfessorshipEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntProfessorshipEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prosProf': !exists(json, 'prosProf') ? undefined : ((json['prosProf'] as Array<any>).map(EntProfessorFromJSON)),
    };
}

export function EntProfessorshipEdgesToJSON(value?: EntProfessorshipEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prosProf': value.prosProf === undefined ? undefined : ((value.prosProf as Array<any>).map(EntProfessorToJSON)),
    };
}


