/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntResults,
    EntResultsFromJSON,
    EntResultsFromJSONTyped,
    EntResultsToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSubjectEdges
 */
export interface EntSubjectEdges {
    /**
     * SubjResu holds the value of the subj_resu edge.
     * @type {Array<EntResults>}
     * @memberof EntSubjectEdges
     */
    subjResu?: Array<EntResults>;
}

export function EntSubjectEdgesFromJSON(json: any): EntSubjectEdges {
    return EntSubjectEdgesFromJSONTyped(json, false);
}

export function EntSubjectEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSubjectEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subjResu': !exists(json, 'subjResu') ? undefined : ((json['subjResu'] as Array<any>).map(EntResultsFromJSON)),
    };
}

export function EntSubjectEdgesToJSON(value?: EntSubjectEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subjResu': value.subjResu === undefined ? undefined : ((value.subjResu as Array<any>).map(EntResultsToJSON)),
    };
}


