/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntSubjectEdges,
    EntSubjectEdgesFromJSON,
    EntSubjectEdgesFromJSONTyped,
    EntSubjectEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSubject
 */
export interface EntSubject {
    /**
     * Code holds the value of the "code" field.
     * @type {number}
     * @memberof EntSubject
     */
    code?: number;
    /**
     * Creditpiont holds the value of the "creditpiont" field.
     * @type {number}
     * @memberof EntSubject
     */
    creditpiont?: number;
    /**
     * 
     * @type {EntSubjectEdges}
     * @memberof EntSubject
     */
    edges?: EntSubjectEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntSubject
     */
    id?: number;
    /**
     * Subjects holds the value of the "subjects" field.
     * @type {string}
     * @memberof EntSubject
     */
    subjects?: string;
}

export function EntSubjectFromJSON(json: any): EntSubject {
    return EntSubjectFromJSONTyped(json, false);
}

export function EntSubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSubject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'creditpiont': !exists(json, 'creditpiont') ? undefined : json['creditpiont'],
        'edges': !exists(json, 'edges') ? undefined : EntSubjectEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'subjects': !exists(json, 'subjects') ? undefined : json['subjects'],
    };
}

export function EntSubjectToJSON(value?: EntSubject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'creditpiont': value.creditpiont,
        'edges': EntSubjectEdgesToJSON(value.edges),
        'id': value.id,
        'subjects': value.subjects,
    };
}


