/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntActivity,
    EntActivityFromJSON,
    EntActivityFromJSONTyped,
    EntActivityToJSON,
    EntYear,
    EntYearFromJSON,
    EntYearFromJSONTyped,
    EntYearToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTermEdges
 */
export interface EntTermEdges {
    /**
     * TermYear holds the value of the term_year edge.
     * @type {Array<EntYear>}
     * @memberof EntTermEdges
     */
    termYear?: Array<EntYear>;
    /**
     * YearActi holds the value of the year_acti edge.
     * @type {Array<EntActivity>}
     * @memberof EntTermEdges
     */
    yearActi?: Array<EntActivity>;
}

export function EntTermEdgesFromJSON(json: any): EntTermEdges {
    return EntTermEdgesFromJSONTyped(json, false);
}

export function EntTermEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTermEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'termYear': !exists(json, 'termYear') ? undefined : ((json['termYear'] as Array<any>).map(EntYearFromJSON)),
        'yearActi': !exists(json, 'yearActi') ? undefined : ((json['yearActi'] as Array<any>).map(EntActivityFromJSON)),
    };
}

export function EntTermEdgesToJSON(value?: EntTermEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'termYear': value.termYear === undefined ? undefined : ((value.termYear as Array<any>).map(EntYearToJSON)),
        'yearActi': value.yearActi === undefined ? undefined : ((value.yearActi as Array<any>).map(EntActivityToJSON)),
    };
}


