/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntActivity,
    EntActivityFromJSON,
    EntActivityFromJSONTyped,
    EntActivityToJSON,
    EntResults,
    EntResultsFromJSON,
    EntResultsFromJSONTyped,
    EntResultsToJSON,
    EntTerm,
    EntTermFromJSON,
    EntTermFromJSONTyped,
    EntTermToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntYearEdges
 */
export interface EntYearEdges {
    /**
     * YearActi holds the value of the year_acti edge.
     * @type {Array<EntActivity>}
     * @memberof EntYearEdges
     */
    yearActi?: Array<EntActivity>;
    /**
     * YearResu holds the value of the year_resu edge.
     * @type {Array<EntResults>}
     * @memberof EntYearEdges
     */
    yearResu?: Array<EntResults>;
    /**
     * YearTerm holds the value of the year_term edge.
     * @type {Array<EntTerm>}
     * @memberof EntYearEdges
     */
    yearTerm?: Array<EntTerm>;
}

export function EntYearEdgesFromJSON(json: any): EntYearEdges {
    return EntYearEdgesFromJSONTyped(json, false);
}

export function EntYearEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntYearEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'yearActi': !exists(json, 'yearActi') ? undefined : ((json['yearActi'] as Array<any>).map(EntActivityFromJSON)),
        'yearResu': !exists(json, 'yearResu') ? undefined : ((json['yearResu'] as Array<any>).map(EntResultsFromJSON)),
        'yearTerm': !exists(json, 'yearTerm') ? undefined : ((json['yearTerm'] as Array<any>).map(EntTermFromJSON)),
    };
}

export function EntYearEdgesToJSON(value?: EntYearEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'yearActi': value.yearActi === undefined ? undefined : ((value.yearActi as Array<any>).map(EntActivityToJSON)),
        'yearResu': value.yearResu === undefined ? undefined : ((value.yearResu as Array<any>).map(EntResultsToJSON)),
        'yearTerm': value.yearTerm === undefined ? undefined : ((value.yearTerm as Array<any>).map(EntTermToJSON)),
    };
}


