// Code generated by entc, DO NOT EDIT.

package term

const (
	// Label holds the string label denoting the term type in the database.
	Label = "term"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSemester holds the string denoting the semester field in the database.
	FieldSemester = "semester"

	// EdgeTermResu holds the string denoting the term_resu edge name in mutations.
	EdgeTermResu = "term_resu"

	// Table holds the table name of the term in the database.
	Table = "terms"
	// TermResuTable is the table the holds the term_resu relation/edge.
	TermResuTable = "results"
	// TermResuInverseTable is the table name for the Results entity.
	// It exists in this package in order to avoid circular dependency with the "results" package.
	TermResuInverseTable = "results"
	// TermResuColumn is the table column denoting the term_resu relation/edge.
	TermResuColumn = "term_term_resu"
)

// Columns holds all SQL columns for term fields.
var Columns = []string{
	FieldID,
	FieldSemester,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Term type.
var ForeignKeys = []string{
	"year_year_term",
}

var (
	// SemesterValidator is a validator for the "semester" field. It is called by the builders before save.
	SemesterValidator func(int) error
)
